---
- name: Установка MySQL
  action: apt pkg={{ item }} state=latest
  with_items:
      - python-mysqldb
      - mysql-client
      - mysql-server
  notify : restart mysql

- name: service Mysql is started
  service: name=mysql state=started enabled=yes

- name: установка конфига my.cnf
  action: template src='mysqld-ansible.cnf.j2' dest='/etc/mysql/conf.d/mysqld-ansible.cnf'
  notify: restart mysql

- name: update mysql root password for all root accounts
  mysql_user: name={{ mysql_root_user }} host=localhost password={{ mysql_root_pass }}

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Установка phpMyAdmin
  action: apt pkg=phpmyadmin state=latest
  notify:
    - nginx restart