- name: Устанаваливаем php пакеты
  apt: pkg={{ item }} state=present
  with_items:
    - php5-fpm
    - php5-cli
    - php5-common
    - php5-curl
    - php5-gd
    - php5-geoip
    - php5-gmp
    - php5-imagick
    - php5-intl
    - php5-json
    - php5-mcrypt
    - php5-memcache
    - php5-memcached
    - php5-redis
    - php5-mysql
    - php5-xdebug
    - php5-sqlite
    - php-apc
    - php-pear
    - php5-pgsql
    - php5-redis
    - php5-dev
    - sqlite3

- name: Устанаваливаем Composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=0755 validate_certs=no

- name: add GitHub Auth token
  shell: composer config -g github-oauth.github.com {{ github_oauth_token }}
  when: github_oauth_token is defined
  sudo_user: vagrant

- name: Устанаваливаем Composer Asset Plugin
  shell: "composer global require 'fxp/composer-asset-plugin:1.0.0-beta3'"
  sudo_user: vagrant

- name: Копируем pool конфиг php-fpm
  template: src=www.conf dest=/etc/php5/fpm/pool.d/
  notify: restart php-fpm

- name: Включаем php модули
  shell: php5enmod {{ item }}
  with_items:
    - mcrypt
  notify:
    - restart php-fpm

- name: Запуск php-fpm
  service: name=php5-fpm state=started enabled=true

- name: конфиг PHP
  template: src=php.ini dest=/etc/php5/fpm/conf.d/custom.ini
  notify:
    - restart php-fpm
  tags: php

- name: chown PHP-FPM sessions dir
  shell: chown vagrant:vagrant /var/lib/php5 -Rf
  tags: php