- name: Устанаваливаем php пакеты
  apt: pkg={{ item }} state=present
  with_items:
    - php5-fpm
    - php5-cli
    - php5-common
    - php5-curl
    - php5-gd
    - php5-geoip
    - php5-gmp
    - php5-imagick
    - php5-intl
    - php5-json
    - php5-mcrypt
    - php5-memcache
    - php5-memcached
    - php5-redis
    - php5-mysql
    - php5-xdebug
    - php5-sqlite
    - php-apc
    - php-pear

- name: Устанаваливаем Composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=0755 validate_certs=no

- name: Копируем pool конфиг php-fpm
  template: src=www.conf dest=/etc/php5/fpm/pool.d/
  notify: restart php-fpm

- name: Запуск php-fpm
  service: name=php5-fpm state=started enabled=true