- name: Устанаваливаем системные пакеты
  apt: pkg={{ item }} state=present
  with_items:
    - htop
    - nmap
    - ntp
    - mc
    - htop
    - iotop
    - iftop
    - atop
    - wget
    - curl
    - git
    - language-pack-ru