---
- hosts: all
  user: vagrant
  sudo: true
  gather_facts: no
  vars_files:
    - defaults/variables.yml
  roles:
    - system
    - npm
    - php
    - phpredis
    - redis
    - gearman
    - php-pecl
    - memcached
    - postgresql
    - mysql
    - nginx